sudo: required
dist: trusty
addons:
  chrome: stable
  before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
addons:
  chrome: stable

language: node_js

cache: yarn

node_js:
  - 6
  - 8
  - 10

script:
  - yarn run test:ci
